docs: providers section textual and visual improvements
daytonaio/docs pull request #102
Opened 2024-08-04 12:19 UTC by stefanicjuraj

- added textual additions and improvements per each sub-section
- added visual outputs when executing the cli commands with explanations
- added list targets section with `daytona target list` command with its descriptions and cli commands
- organized the structure of content
- fixed inter-linking between sections (fyi: this is already covered by this issue: https://github.com/daytonaio/docs/issues/92, but was unsure whether it will get merged [if yes, i can delete this fix so there are no conflicts])
- all changes have been tested and previewed locally

2024-08-04 15:44 UTC, ivan-burazin approved these changes

2024-08-07 07:21 UTC, Tpuljak requested changes

2024-08-07 07:21 UTC, Tpuljak commented on src/content/docs/configuration/providers.mdx
> +        ┃ Remote Private Key Path
I think we can remove `┃` since it's just a focus indicator.

2024-08-07 07:21 UTC, Tpuljak commented on src/content/docs/configuration/providers.mdx
> +Daytona allows you to delete Targets, helping you manage and remove those that are no longer needed. Once a Target is deleted, you will not be able to manage or deploy Workspaces without adding anoth
> Once a Target is deleted, you will not be able to manage or deploy Workspaces without adding another Target with the same configuration.

This is a bit harsh. You can manage workspaces on other targets but this sentence makes it seem like your completely blocked if you remove any target.

I suggest rephrasing so its clear that you can not manage workspace on that target only.

2024-08-08 07:42 UTC, Tpuljak approved these changes

2024-08-08 07:43 UTC, merged