docs: modify support anchor tag hyperlink
daytonaio/docs pull request #103
Opened 2024-08-04 12:30 UTC by stefanicjuraj

- modified "Need help? - Reach support" anchor tag hyperlink to link to daytona's slack community

This can be modified to link to any other support communication channel of preference (GitHub repository, issues, email, etc.)

2024-08-04 15:23 UTC, ivan-burazin approved these changes

2024-08-07 07:16 UTC, Tpuljak requested changes

2024-08-07 07:16 UTC, Tpuljak commented on src/components/Footer.astro
> +        href="https://join.slack.com/t/daytonacommunity/shared_invite/zt-273yohksh-Q5YSB5V7tnQzX2RoTARr7Q"
Please use `https://go.daytona.io/slack` because the join.slack.com link expires often so we just update it in the go.daytona.io redirect link.

2024-08-08 07:39 UTC, Tpuljak approved these changes

2024-08-08 07:39 UTC, merged