docs: add individual ide process
daytonaio/docs pull request #111
Opened 2024-08-10 21:06 UTC by stefanicjuraj

- added individual process for each IDE  (`/usage/ide#vs-code`, `/usage/ide#vs-code-browser`,...)

2024-08-12 11:34 UTC, ivan-burazin approved these changes

2024-08-12 11:40 UTC, ivan-burazin approved these changes

2024-08-13 06:58 UTC, Tpuljak requested changes

2024-08-13 06:58 UTC, Tpuljak commented on src/content/docs/usage/ide.mdx
> +    Upon running this command, Daytona will display a list of available IDEs, allowing you to select `VS Code` as your default choice.
`VS Code - Browser`

2024-08-13 06:58 UTC, Tpuljak commented on src/content/docs/usage/ide.mdx
> +Daytona allows you to connect to your Workspace using Terminal SSH.
`Daytona allows you to connect to your Workspace using Terminal SSH.` => `Daytona allows you to connect to your Workspace through SSH`.

2024-08-13 06:58 UTC, Tpuljak commented on src/content/docs/usage/ide.mdx
> +    You can now use the `daytona code` command to automatically open the Terminal SSH already connected to your Workspace.
`You can now use the `daytona code` command to automatically open the Terminal SSH` => `... to start an SSH session`.

2024-08-13 06:58 UTC, Tpuljak commented on src/content/docs/usage/ide.mdx
> +## Terminal SSH
Terminal SSH is a bit special so it doesn't follow the "template" from above

2024-08-13 16:25 UTC, ivan-burazin approved these changes

2024-08-14 08:37 UTC, Tpuljak approved these changes

2024-08-14 08:37 UTC, merged