docs: cli section textual and visual improvements
daytonaio/docs pull request #112
Opened 2024-08-10 21:30 UTC by stefanicjuraj

- cli description rewrite
- added cli successful output examples
- added project config commands (https://github.com/daytonaio/docs/issues/98) - let me know if you have a suggestion where the project config guide could reside within the documentation - perhaps in workspaces as it is a related section?

2024-08-13 07:05 UTC, Tpuljak requested changes

2024-08-13 07:05 UTC, Tpuljak commented on src/content/docs/reference/cli.mdx
This file is autogenerated from https://github.com/daytonaio/daytona/tree/main/docs by running `yarn update-cli-reference` (same thing for `yarn update-server-reference`). Because of this, manually editing this file is not an option.

Can you find an example of another product that has output examples in CLI references?

P.S. Yes, we forgot to update this file in the last release 😅

2024-08-13 14:34 UTC, stefanicjuraj commented on src/content/docs/reference/cli.mdx
Hi, I only saw the initial commit regarding adding all CLI commands at once, which seemed to be a manual process (I could be wrong). https://github.com/daytonaio/docs/commit/177c1f98ec80b98e2b8e92c85f56a348c058f61d

I couldn't find any other CLI updates in the documentation. The CLI seems to have [only a few commits since the start](https://github.com/daytonaio/docs/commits/main/src/content/docs/reference/cli.mdx), and none being its updates?

I think we can close this pull request for now, and once the CLI commands are updated using the script, we can think of ways how to improve the script generation to include better visual and textual improvements to the CLI - let me know what you think about this. 😁

Regarding output examples in CLI references, I agree that it does not seem like a common practice, but I started seeing it more often listed in the form of visual aid and examples:
https://docs.docker.com/reference/cli/docker/#display-help-text
https://docs.gitlab.com/runner/commands/
https://docs.aws.amazon.com/cli/latest/reference/amplify/create-app.html#output

2024-08-13 16:24 UTC, ivan-burazin commented on src/content/docs/reference/cli.mdx
I like these examples

2024-08-14 08:36 UTC, Tpuljak commented on src/content/docs/reference/cli.mdx
To be clear, I love the examples but, in this form, this is not maintainable.
I would close this for know and we can think of ways to automate this.

The docker and gitlab links you sent are, for sure, manually maintained.
We could do some sort of hybrid workflow, but I would leave this as is for know and focus on other things.

2024-08-15 20:04 UTC, closed without merging