docs/lois
daytonaio/docs pull request #12
Opened 2024-01-05 19:31 UTC by zmzlois

Update

vscode: 
- based on extension updates
- add SSH connection

Added
- jetbrains
- idps

2024-01-08 15:45 UTC, nkkko requested changes
We appreciate the effort, it is clear that you did a lot of work. But it makes it hard to coordinate considering the number of people involved.

Could you please:
- Please clean up and just do a PR with plain docs change.
- Any code change, new components etc. should be done in stages, for example, propose a new components in a separate PR which can then be reviewed by external devs. Only when new components are merged add them to doc files.

2024-01-08 15:45 UTC, nkkko commented on src/content/docs/installation/idps.mdx
> +{/*TODO: All these shit should be just a link click away to set up no? Related excalidraw: https://link.excalidraw.com/l/7LItosJ86GN/2bnFDQd3mNq*/}
Could you please avoid using inappropriate words, even if it is just a comment for yourself? :D Tnx

2024-01-08 15:45 UTC, nkkko commented on src/components/Keyboard.astro
Please avoid adding new components and focus on the docs themself. Any need for new components should be directed to external dev team.

2024-01-10 16:15 UTC, zmzlois commented
closing this to split style + component + plain docs

2024-01-10 16:15 UTC, closed without merging