docs: add cursor ide
daytonaio/docs pull request #143
Opened 2024-09-04 16:33 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/docs/issues/133

2024-09-05 06:53 UTC, Tpuljak approved these changes

2024-09-11 07:46 UTC, Tpuljak commented
@stefanicjuraj lets get the conflicts resolved so we can merge

2024-09-11 09:35 UTC, Tpuljak requested changes

2024-09-11 09:35 UTC, Tpuljak commented on src/content/docs/about/getting-started.mdx
> +<<<<<<< #133-add-cursor-ide
Not sure how this even got through 😅

2024-09-11 09:45 UTC, Tpuljak approved these changes

2024-09-11 15:23 UTC, stefanicjuraj commented
Hi, seems to be working fine locally for me - in the previous pull requests we changed the base path of the oss documentation to `/docs`, so maybe the recent changes weren't propagated for you? - referring to this: https://github.com/daytonaio/docs/pull/140

<img width="708" alt="image" src="https://github.com/user-attachments/assets/0264fc91-a756-4de0-9ea2-d2412e9eb6ab">

2024-09-20 15:34 UTC, ivan-burazin approved these changes

2024-09-20 15:35 UTC, Tpuljak commented
@stefanicjuraj rebase with main and we're good to go

2024-09-20 15:48 UTC, merged