docs: update readme
daytonaio/docs pull request #147
Opened 2024-09-07 21:05 UTC by stefanicjuraj

2024-09-07 22:26 UTC, ivan-burazin approved these changes

2024-09-11 07:56 UTC, Tpuljak requested changes

2024-09-11 07:56 UTC, Tpuljak commented on README.md
> +| :------------------------- | :----------------------------- | :--------------------------------------------------------------------------- |
Remove the `npm` commands column since we have `yarn.lock` committed into the repo

2024-09-11 16:43 UTC, ivan-burazin approved these changes

2024-09-12 07:39 UTC, Tpuljak approved these changes

2024-09-12 07:39 UTC, merged