docs: add workspace multi-projects
daytonaio/docs pull request #159
Opened 2024-09-24 15:02 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/docs/issues/158

2024-09-24 15:25 UTC, Tpuljak commented on src/content/docs/usage/workspaces.mdx
> +Daytona allows you to create a Workspace with multiple projects, enabling you to work on multiple codebases simultaneously within a single environment.
I would add an example of what this means.

e.g. When using the DO provider, multiple projects will be spun up inside the same droplet, AWS - EC2, etc.

2024-09-25 07:57 UTC, Tpuljak requested changes

2024-09-25 07:57 UTC, Tpuljak commented on src/content/docs/usage/workspaces.mdx
> +Daytona allows you to create a Workspace with multiple projects, enabling you to work on multiple codebases simultaneously within a single environment.
`The [Docker Provider](/docs/configuration/providers#docker) deploys projects within the same container.`

This is not correct. There is no workspace in the Docker Provider. Each project is its own container. The "workspace" is the host machine.

2024-09-26 07:06 UTC, Tpuljak approved these changes

2024-09-29 15:34 UTC, ivan-burazin requested changes
@stefanicjuraj @Tpuljak cab we edit this:

Daytona allows you to create a Workspace with multiple projects, enabling you to work on multiple codebases simultaneously within a single environment.

>>

Daytona allows you to create a workspace that contains multiple repositories, which we refer to as projects. This enables you to work on several codebases simultaneously within a single environment.

This will make it more clear to the reader, and also we will rename this to repos anyway.

2024-10-02 09:25 UTC, ivan-burazin approved these changes

2024-10-02 09:37 UTC, merged