docs: builders dev container & modify layout
daytonaio/docs pull request #163
Opened 2024-10-09 18:49 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/enterprise-docs/issues/161

2024-10-11 08:59 UTC, marko-baric-ca commented
Looks good to me

2024-10-11 13:25 UTC, stefanicjuraj commented
@ivan-burazin

2024-10-12 14:09 UTC, ivan-burazin approved these changes

2024-10-14 07:53 UTC, Tpuljak requested changes

2024-10-14 07:53 UTC, Tpuljak commented on src/content/docs/usage/builders.mdx
> +The `devcontainer.json` file is a JSON file that consists of several components that define the development environment. The file includes the following properties:
>  The file includes the following properties:

This seems like it's the only properties it has.

I think we should link to https://containers.dev/implementors/json_reference/ (I see we link to containers.dev below, but the comment still stands here)

2024-10-15 07:21 UTC, Tpuljak approved these changes

2024-10-15 07:21 UTC, merged