docs: remove forward --public flag section
daytonaio/docs pull request #177
Opened 2024-10-14 21:23 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/docs/issues/173

2024-10-15 00:05 UTC, stefanicjuraj commented
@ivan-burazin

2024-10-15 07:28 UTC, Tpuljak requested changes
Seems I didn't make the issue clear enough.

`daytona forward PORT WORKSPACE_NAME PROJECT_NAME` still has `--public`. 
This is how the command is run when you're outside of the project.

When you're inside (e.g. `daytona ssh` or `daytona code`) then the command is:
`daytona forward PORT`. This command is public by default. The commands are different wether ran inside or outside a project.

2024-10-16 07:24 UTC, Tpuljak approved these changes

2024-10-16 18:59 UTC, ivan-burazin approved these changes

2024-10-17 06:26 UTC, merged