docs: add gcp provider & target
daytonaio/docs pull request #188
Opened 2024-11-01 20:58 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/docs/issues/187

2024-11-03 11:21 UTC, ivan-burazin requested changes
can we reorder them:
Docker 
DigitalOcean
AWS 
Azure
GCP
Fly

2024-11-04 07:45 UTC, Tpuljak approved these changes

2024-11-11 08:34 UTC, Tpuljak approved these changes

2024-11-12 09:07 UTC, idagelic approved these changes

2024-11-12 09:08 UTC, merged