docs: add docker extension
daytonaio/docs pull request #191
Opened 2024-11-11 21:42 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/docs/issues/190

2024-11-12 08:35 UTC, Tpuljak requested changes

2024-11-12 08:35 UTC, Tpuljak commented on src/content/docs/tools/docker-extension.mdx
> +Daytona provides a Docker extension for using an embedded version of the Daytona client and server tools directly within the Docker Desktop.
`directly within Docker Desktop`

2024-11-12 08:35 UTC, Tpuljak commented on src/content/docs/tools/docker-extension.mdx
> +View the Daytona Docker extension in the [Docker Desktop Extensions Marketplace](https://open.docker.com/extensions/marketplace?extensionId=daytonaio/docker-extension&tag=0.44.0) or [GitHub repositor
Since its `Docker Desktop Extension Marketplace`, myb we should refer to it as `Docker Extension` instead of `Docker extension`

2024-11-12 17:42 UTC, ivan-burazin commented on src/content/docs/tools/docker-extension.mdx
> +## Create a Workspace
@Tpuljak we dont do screenshots in docs.

2024-11-15 13:44 UTC, ivan-burazin approved these changes

2024-11-18 14:00 UTC, idagelic approved these changes

2024-11-19 08:24 UTC, merged