feat: add update llms(.txt) index (standardize LLM-friendly content)
daytonaio/docs pull request #193
Opened 2024-11-14 22:30 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/docs/issues/192

2024-11-15 07:59 UTC, Tpuljak requested changes

2024-11-15 07:59 UTC, Tpuljak commented on llms.txt
> +
Add short Daytona description here

2024-11-15 07:59 UTC, Tpuljak commented on package.json
> +    "build": "yarn update-llms || true && astro build",
Why `|| true`?

2024-11-15 13:22 UTC, ivan-burazin approved these changes
Approving as Toma will make sure all is set

2024-11-17 12:05 UTC, ivan-burazin approved these changes

2024-11-19 08:16 UTC, Tpuljak approved these changes

2024-11-19 08:16 UTC, merged