feat: search update (index automation & blog)
daytonaio/docs pull request #198
Opened 2024-11-20 22:47 UTC by stefanicjuraj

2024-11-22 07:48 UTC, Tpuljak requested changes

2024-11-22 07:48 UTC, Tpuljak commented on src/components/Search.jsx
![Screenshot 2024-11-22 at 08 45 38](https://github.com/user-attachments/assets/eee24212-5d87-4959-8b25-af2cf486ab09)

This is probably unrelated to this PR but it's more apparent now that we have the blog results.
I suggest that the search bar be sticky when scrolling so it's always in view.

Moreover, a bigger bottom padding would be appreciated so the user can scroll a bit more before reaching the bottom. On larger screens, its a bit unergonomic to read stuff on the very bottom.

2024-11-23 07:50 UTC, ivan-burazin approved these changes

2024-11-24 07:16 UTC, ivan-burazin approved these changes

2024-11-25 11:35 UTC, Tpuljak approved these changes

2024-11-25 11:36 UTC, merged