docs: add architecture diagram
daytonaio/docs pull request #214
Opened 2024-12-24 23:14 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/docs/issues/213

2024-12-25 00:03 UTC, stefanicjuraj commented
@ivan-burazin

2025-01-04 09:58 UTC, ivan-burazin requested changes
architecture should be its own section in the docs

2025-01-09 06:07 UTC, ivan-burazin requested changes
<img width="297" alt="Screenshot 2025-01-09 at 07 05 54" src="https://github.com/user-attachments/assets/c8c9c9dc-790d-4e11-9fba-a77dd1190d57" />
Apologies I meant I would put it here on the main menu between What is Daytona and Getting started. thanks!

2025-01-09 21:00 UTC, ivan-burazin approved these changes

2025-01-10 15:39 UTC, Tpuljak requested changes

2025-01-10 15:39 UTC, Tpuljak commented on src/content/docs/about/architecture.mdx
> +### Container Registries
Update this based on the feedback from the Container Registries branch

2025-01-10 15:39 UTC, Tpuljak commented on src/content/docs/about/architecture.mdx
> +<Image
The image is very high res but the size of the image itself isn't big enough to be clear.

I suggest that we add the ability to click on the image that would open a modal with a full-screen image

2025-01-11 07:50 UTC, ivan-burazin approved these changes

2025-01-12 18:33 UTC, ivan-burazin approved these changes

2025-01-13 08:53 UTC, Tpuljak commented on src/content/docs/about/architecture.mdx
> +### Container Registries
@stefanicjuraj this should be the description: `Container registries store credentials used to pull container images from specified registry servers. Adding container registry credentials is useful for users who want to create Workspaces from private images and those hosted on private registries.
`

2025-01-13 16:15 UTC, Tpuljak commented on src/content/docs/about/architecture.mdx
> +<Image
@stefanicjuraj let's add cursor pointer when hovering over the image and we're good to go

2025-01-13 16:16 UTC, Tpuljak requested changes

2025-01-13 16:16 UTC, Tpuljak commented on src/content/docs/about/architecture.mdx
> +Supported Container Registries include Google Container Registry, Azure Container Registry, Amazon Elastic Container Registry, Docker Hub, and others.
We can remove this line. We support all container registries.

2025-01-13 16:50 UTC, Tpuljak approved these changes

2025-01-13 16:51 UTC, merged