docs: add container registries
daytonaio/docs pull request #215
Opened 2024-12-25 00:03 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/docs/issues/206

2024-12-25 00:03 UTC, stefanicjuraj commented
@ivan-burazin

2025-01-04 09:59 UTC, ivan-burazin approved these changes

2025-01-07 07:53 UTC, Tpuljak requested changes

2025-01-07 07:53 UTC, Tpuljak commented on src/content/docs/configuration/container-registries.mdx
Container registries in Daytona are not used to deploy anything nor do they depend on dev, testing or prod environments.

Container registries in Daytona are simply credentials that are used when pulling images from specified registry servers.

e.g. If you want to use a private image to create a workspace, you need to add the appropriate credentials for Daytona to be able to pull that image.

2025-01-09 08:13 UTC, Tpuljak commented on src/content/docs/configuration/container-registries.mdx
```
Daytona's architecture allows you to configure multiple container registries. This allows you to use different registries for different environments, such as development, testing, and production.
```

Replace this section with this:
```
Adding container registry credentials is useful for users who want to create workspaces from private images and those hosted on private registries.
```

2025-01-10 09:36 UTC, Tpuljak approved these changes

2025-01-10 09:36 UTC, merged