docs: add samples
daytonaio/docs pull request #218
Opened 2024-12-26 20:25 UTC by stefanicjuraj

Fixes https://github.com/daytonaio/docs/issues/189

2024-12-26 20:25 UTC, stefanicjuraj commented
@Tpuljak @ivan-burazin

2025-01-04 09:51 UTC, ivan-burazin approved these changes

2025-01-07 07:46 UTC, Tpuljak requested changes

2025-01-07 07:46 UTC, Tpuljak commented on src/content/docs/usage/samples.mdx
> +    "name": "My Custom Sample",
`"description"` property missing

2025-01-07 07:46 UTC, Tpuljak commented on src/content/docs/usage/samples.mdx
> +Daytona Samples are integrated via Samples Index (`index.json`) file that serves as a registry of available Daytona Samples for creating Workspaces.
`via a Samples Index`

2025-01-07 07:46 UTC, Tpuljak commented on src/content/docs/usage/samples.mdx
> +The chosen Sample will be cloned and used to create the Workspace. Daytona Sample repository will serve as the core content of the Sample used to create a Workspace.
`The Daytona Sample repository`

2025-01-07 07:46 UTC, Tpuljak commented on src/content/docs/usage/samples.mdx
> +4. Host the Sample repository publicly on a Git repository or another platform.
The Sample doesn't have to be public.

Users can host private samples as well. The only requirement is that they have access to that repo when they create a workspace

2025-01-09 08:11 UTC, Tpuljak approved these changes

2025-01-09 08:11 UTC, merged