add microsoft/azure as idp and style edit
daytonaio/docs pull request #25
Opened 2024-01-20 02:55 UTC by zmzlois

## What's added in this PR?

- left side bar style based on Ivan's suggestion
- add microsoft as idp

2024-01-20 10:29 UTC, buraz82 commented on src/components/SidebarSublist.astro
Can we use the term Azure Active Directory instead of Azure?

2024-01-20 15:01 UTC, loisisar commented on src/components/SidebarSublist.astro
good shout

2024-01-20 15:03 UTC, loisisar commented on src/content/docs/installation/idps.mdx
> +## Azure
Change this to Azure Active Directory

2024-01-20 20:45 UTC, nkkko approved these changes

2024-01-21 13:55 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +Within a Daytona deployment, teams share a cohesive environment where team members can share [workspaces](/usage/workspaces), collaborate, and manage workspaces. On Daytona dashboard, you can invite,
@zmzlois this is not true.

2024-01-21 13:56 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +Before you start configuring teams, make sure you have the following:
@zmzlois make sure you have access to a Daytona deployment

2024-01-21 13:58 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +Once you have a Daytona deployment, you can access the **daytona dashboard**: we will be refering to your Daytona dashboard as `https://domain.com`.
we should keep the url across docs: "https://daytona.example.com"

2024-01-21 14:00 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +[//]: # ({/*TODO: docs - second list item should be corrected rendered and indented*/})
@zmzlois We need create teams first then manage teams then delete teams. Also feels like the horizonal seperater that you used on IDPs is missing

2024-01-21 14:02 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +On different IDEs that utilises Daytona's [VS Code extension](/tools/vs-code-extension) or [JetBrain's Gateway Plugin](/tools/jetbrains-gateway), at the moment you will be able to:
We dont need to link twice to the plugins. rather just an intro that you can do this via the ides and then the segments below for each

2024-01-21 14:04 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +At the moment, all the team related configuration can be only done on Daytona dashboard or Keycloak. You won't be able to configure teams from IDEs.
@zmzlois this is incorrect. Team are not correlated with Keycloak

2024-01-21 14:05 UTC, ivan-burazin requested changes
@zmzlois Comments added.

2024-01-21 15:24 UTC, zmzlois commented on src/content/docs/configuration/teams.md
> +At the moment, all the team related configuration can be only done on Daytona dashboard or Keycloak. You won't be able to configure teams from IDEs.
my bad.

2024-01-21 15:32 UTC, zmzlois commented on src/content/docs/configuration/teams.md
> +Within a Daytona deployment, teams share a cohesive environment where team members can share [workspaces](/usage/workspaces), collaborate, and manage workspaces. On Daytona dashboard, you can invite,
fixing

2024-01-21 18:05 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
>  title: Teams Configuration
Title should be just Teams

2024-01-21 18:15 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +On Daytona dashboard, users can invite, manage and configure team members, become a owner of a team, and the configuration is synced across all your [IDEs](/usage/ides) that are connected to your Day
This first section is always the Overview. In the over view it should first explain what is the purpose of the feature  and then what can be done with it.

here is my edit for this:

A team represents a group of people collaborating together in Daytona, either as an internal unit like the Engineering department or as an external group, such as a team of Open Source Collaborators.

By creating a team, you become the team owner. This role empowers you to invite, manage, and configure team members, and most importantly, to manage the hardware resources at their disposal.

2024-01-21 18:18 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +## Pre-requisites
@zmzlois you changed the way you spelled and the way you presented  "prerequisites" this should be consistant across docs.

2024-01-21 18:20 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +In this section, we will walk you through how you can invite, assign roles, and remove team members from your daytona dashboard. Whenever you register an account on a Daytona deployment, you are defa
@zmzlois  this section feels out of place. as firs you need to Create a team to manage it. Also I feel that nost of this fits in the Overview anyway

2024-01-21 18:22 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +- Click on your **team'name** in the top right corner.
@zmzlois **team'name**  is spelt wrong. Also by default its "My Team" so you can add that in there

2024-01-21 18:25 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +:::note
This is incorrect. Some people will have a licence, so it should be informative as in "if you get an error ... if interested in an upgrade book a demo https://daytona.zapier.app/

2024-01-21 18:28 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
> +
@zmzlois I feel that here we should explain now that you create a new team or using the default my team you can mange it from the left sidebar. Under Team you will find subscription, members and settings.

And then break down the next sections

2024-01-21 18:29 UTC, ivan-burazin requested changes
Added comments for review

2024-01-21 18:33 UTC, ivan-burazin commented on src/content/docs/usage/account.md
> +
@zmzlois  Account is missing the Overview, what is an account why is it here and what te user can do with it

2024-01-21 18:34 UTC, ivan-burazin commented on src/content/docs/usage/account.md
> +## Managing secrets
Also missing the entire settings section and SSH

2024-01-21 18:35 UTC, ivan-burazin requested changes
Account settings missing

2024-01-21 22:08 UTC, zmzlois commented on src/content/docs/usage/account.md
> +
account is not finished. patched in next PR. just moved the secret bit there

2024-01-21 22:22 UTC, zmzlois commented on src/content/docs/usage/account.md
> +## Managing secrets
I wrote the secrets part in workspaces just moved them to accounts, guide for account is not finished

2024-01-22 00:49 UTC, zmzlois commented on src/content/docs/configuration/teams.md
> +
I am removing the **Managing team** and have all of them separate as <h2>

2024-01-22 10:42 UTC, zmzlois commented
Reformatted Jetbrains Gateway

2024-01-22 11:13 UTC, zmzlois commented on src/content/docs/configuration/teams.md
> +
This part might better off use a table

2024-01-22 16:05 UTC, closed without merging