docs: templates update
daytonaio/docs pull request #45
Opened 2024-01-25 20:52 UTC by zmzlois

# What's changed in this PR

- Remove *Creating workspace from templates* in templates guide
- Add templates index explaination and folder structure
- Add custom script to update templates

2024-01-26 14:20 UTC, ivan-burazin commented on src/content/docs/configuration/templates.mdx
> +Below is an indexed description of the default templates, their content and repository URLs.
@zmzlois please remove the list of current templates. non important

2024-01-26 14:21 UTC, ivan-burazin commented on src/content/docs/configuration/templates.mdx
> +### Deploy with Terraform
@zmzlois remove everything connected to Terraform

2024-01-26 14:21 UTC, ivan-burazin requested changes
Comments what needs to be removed

2024-01-26 19:03 UTC, zmzlois commented
removed, @nkkko

2024-01-29 20:17 UTC, ivan-burazin approved these changes

2024-01-30 10:31 UTC, merged