docs/account: initial docset
daytonaio/docs pull request #50
Opened 2024-01-27 22:59 UTC by d4yt0nad0cs

2024-01-28 08:02 UTC, ivan-burazin commented on src/content/docs/usage/account.md
> +:::danger
@d4yt0nad0cs we use the term Caution instead of Danger

2024-01-28 08:02 UTC, ivan-burazin requested changes
@d4yt0nad0cs Can we we limit number of Headings (that show up in the right side bar), and also make them shorter and that sense easier to read?

So we would go from :
Overview
Choosing the default editor used to connect to workspaces
Configuring the default dotfiles repository for new workspaces
Sharing a common environment variable across workspaces
Editing a global environment variable
Removing a global environment variable
Adding an SSH public key to your account
Removing an SSH public key from your account
Connecting an additional Git provider to your account
Disconnecting a Git provider from your account
Deleting your account

To
Overview
Setting IDE
Adding Dotfiles
Adding Environment Variables 
Adding SSH Public Key 
Connecting an Git provider 
Deleting your Account

With this there would be needed substions to be created (add edit delete) and perhaps even a intro sentence for each heading. But would be easier to navigate for the user.

2024-01-28 09:23 UTC, d4yt0nad0cs commented
@ivan-burazin latest commit shortens the headings and restructures slightly into sections.

2024-01-29 18:46 UTC, ivan-burazin approved these changes
@nkkko I would approve this just please set titles to "title case" also shorted "Choosing the default editor" to Default IDE" to be consistent

cc @d4yt0nad0cs tagging you just for future reference

2024-01-29 18:55 UTC, merged