configuration/teams: rm dangling sentence
daytonaio/docs pull request #51
Opened 2024-01-27 23:00 UTC by d4yt0nad0cs

2024-01-28 08:07 UTC, ivan-burazin requested changes
Slight editing needed.

2024-01-28 08:07 UTC, ivan-burazin commented on src/content/docs/configuration/teams.md
>  If you have deployed Daytona as a *[Single Node installation](/installation/single-node)*, your instance will use Daytona's free tier subscription.
@d4yt0nad0cs i would remove "If you have deployed Daytona as a *[Single Node installation](/installation/single-node)*, your instance will use Daytona's free tier subscription."

And just state NOTE instead of TIP
All Daytona deployments are initially configured with the Non-Commercial License by default. For more information about this license, please visit [Daytona's End User License Agreement](https://www.daytona.io/eula). If you wish to upgrade your license, please reach out to Daytona.

2024-01-28 09:26 UTC, d4yt0nad0cs commented on src/content/docs/configuration/teams.md
>  If you have deployed Daytona as a *[Single Node installation](/installation/single-node)*, your instance will use Daytona's free tier subscription.
Resolved in [c8ff29a](https://github.com/daytonaio/docs/pull/51/commits/c8ff29abdab1bb8b842e2d344e099e7e8ef0b43c).

2024-01-29 19:36 UTC, ivan-burazin approved these changes
approve but same comment about titles @nkkko & @d4yt0nad0cs

2024-01-30 08:49 UTC, merged