add workspace create flags usage tip
daytonaio/docs pull request #79
Opened 2024-06-21 16:09 UTC by lbrecic

![2024-06-21_18-09](https://github.com/daytonaio/docs/assets/116551028/21bc6954-86d7-41cf-811b-1981be0e46c2)

2024-06-25 16:41 UTC, Tpuljak approved these changes

2024-06-26 12:03 UTC, osslate commented on src/content/docs/usage/workspaces.mdx
> +- `--builder` flag sets one of the available builder choices (currently: auto/devcontainer/none)
```suggestion
You can set the Project Builder at Workspace creation time using command-line flags.
These flags only apply when creating Workspaces with a single Project.

-   To use the Custom Image Builder, set both `--custom-image` and `--custom-image-user` flags.
-   To use the Dev Container Builder, set the`--devcontainer-path` flag to the Dev Container configuration path within the repository.
-   To explicitly specify the Builder, set the`--builder` flag.
    Accepted values are `auto`, `devcontainer`, or `none`. 
```

2024-06-26 12:05 UTC, osslate requested changes
Thank you for the contribution! The technical information is perfect, I've just left some phrasing changes. Once they're accepted this is good to merge.

This likely won't live as an admonition/tip in the future, but for now I'm fine merging it.

2024-06-28 10:04 UTC, ivan-burazin approved these changes

2024-06-28 10:13 UTC, merged